version: "3"

services:
  frontend:
    build: .
    environment:
      - NODE_ENV=development
    volumes:
      - ./app/:/usr/src/anagramee_front
    command: yarn start
    ports:
      - "3000:3000"
    tty: true
